[2024-07-14T09:05:26.804+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T09:05:26.858+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T03:50:00+00:00 [queued]>
[2024-07-14T09:05:26.907+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T03:50:00+00:00 [queued]>
[2024-07-14T09:05:26.917+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T09:05:26.973+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 03:50:00+00:00
[2024-07-14T09:05:27.025+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3556) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-14T09:05:27.023+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T03:50:00+00:00', '--job-id', '1142', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpfudd3cw_']
[2024-07-14T09:05:27.037+0000] {standard_task_runner.py:91} INFO - Job 1142: Subtask save_and_flush_task
[2024-07-14T09:05:27.035+0000] {standard_task_runner.py:63} INFO - Started process 3583 to run task
[2024-07-14T09:05:27.161+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T03:50:00+00:00 [running]> on host d537c34a4880
[2024-07-14T09:05:27.357+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T03:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T03:50:00+00:00'
[2024-07-14T09:05:27.359+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T09:05:27.361+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T09:05:27.368+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T09:05:27.401+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T03:50:00+00:00, execution_date=20240714T035000, start_date=20240714T090526, end_date=20240714T090527
[2024-07-14T09:05:27.479+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T09:05:27.503+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T09:05:27.508+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-14T20:34:44.847+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T20:34:44.868+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T03:50:00+00:00 [queued]>
[2024-07-14T20:34:44.873+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T03:50:00+00:00 [queued]>
[2024-07-14T20:34:44.874+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T20:34:44.883+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 03:50:00+00:00
[2024-07-14T20:34:44.888+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1720) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T20:34:44.889+0000] {standard_task_runner.py:63} INFO - Started process 1727 to run task
[2024-07-14T20:34:44.890+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T03:50:00+00:00', '--job-id', '760', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpswr3pqsd']
[2024-07-14T20:34:44.900+0000] {standard_task_runner.py:91} INFO - Job 760: Subtask save_and_flush_task
[2024-07-14T20:34:44.952+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T03:50:00+00:00 [running]> on host 77caf7e4b282
[2024-07-14T20:34:45.025+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T03:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T03:50:00+00:00'
[2024-07-14T20:34:45.027+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T20:34:45.034+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T20:34:45.035+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T20:34:45.044+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T03:50:00+00:00, execution_date=20240714T035000, start_date=20240714T203444, end_date=20240714T203445
[2024-07-14T20:34:45.078+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T20:34:45.096+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T20:34:45.099+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-15T06:31:25.955+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T06:31:25.975+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T03:50:00+00:00 [queued]>
[2024-07-15T06:31:25.980+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T03:50:00+00:00 [queued]>
[2024-07-15T06:31:25.980+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-15T06:31:25.988+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 03:50:00+00:00
[2024-07-15T06:31:25.992+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2777) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-15T06:31:25.994+0000] {standard_task_runner.py:63} INFO - Started process 2779 to run task
[2024-07-15T06:31:25.993+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T03:50:00+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/et_dag.py', '--cfg-path', '/tmp/tmp8ma6odvs']
[2024-07-15T06:31:25.996+0000] {standard_task_runner.py:91} INFO - Job 129: Subtask save_and_flush_task
[2024-07-15T06:31:26.063+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T03:50:00+00:00 [running]> on host 52e7a9c3d832
[2024-07-15T06:31:26.141+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T03:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T03:50:00+00:00'
[2024-07-15T06:31:26.143+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T06:31:26.151+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T06:31:26.156+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/et_dag.py", line 38, in trigger_save_and_flush
    logging('Invoking method to save data from records')
TypeError: 'module' object is not callable
[2024-07-15T06:31:26.175+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T03:50:00+00:00, execution_date=20240714T035000, start_date=20240715T063125, end_date=20240715T063126
[2024-07-15T06:31:26.201+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 129 for task save_and_flush_task ('module' object is not callable; 2779)
[2024-07-15T06:31:26.224+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-15T06:31:26.252+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-15T06:31:26.256+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-15T07:09:39.732+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T07:09:39.750+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T03:50:00+00:00 [queued]>
[2024-07-15T07:09:39.755+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T03:50:00+00:00 [queued]>
[2024-07-15T07:09:39.756+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-15T07:09:39.764+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 03:50:00+00:00
[2024-07-15T07:09:39.769+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=301) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-15T07:09:39.769+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T03:50:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/et_dag.py', '--cfg-path', '/tmp/tmp4xw3yegn']
[2024-07-15T07:09:39.771+0000] {standard_task_runner.py:63} INFO - Started process 306 to run task
[2024-07-15T07:09:39.771+0000] {standard_task_runner.py:91} INFO - Job 42: Subtask save_and_flush_task
[2024-07-15T07:09:39.806+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T03:50:00+00:00 [running]> on host 07ee111a4cec
[2024-07-15T07:09:39.870+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T03:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T03:50:00+00:00'
[2024-07-15T07:09:39.872+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T07:09:39.883+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T07:09:39.883+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/et_dag.py", line 38, in trigger_save_and_flush
    logging('Invoking method to save data from records')
TypeError: 'module' object is not callable
[2024-07-15T07:09:39.891+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T03:50:00+00:00, execution_date=20240714T035000, start_date=20240715T070939, end_date=20240715T070939
[2024-07-15T07:09:39.941+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 42 for task save_and_flush_task ('module' object is not callable; 306)
[2024-07-15T07:09:39.954+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-15T07:09:39.968+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-15T07:09:39.970+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
