[2024-07-14T09:05:35.380+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T09:05:35.401+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T07:00:00+00:00 [queued]>
[2024-07-14T09:05:35.410+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T07:00:00+00:00 [queued]>
[2024-07-14T09:05:35.412+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T09:05:35.423+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 07:00:00+00:00
[2024-07-14T09:05:35.430+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3611) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-14T09:05:35.431+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T07:00:00+00:00', '--job-id', '1161', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpqm5r2vxs']
[2024-07-14T09:05:35.433+0000] {standard_task_runner.py:63} INFO - Started process 3636 to run task
[2024-07-14T09:05:35.433+0000] {standard_task_runner.py:91} INFO - Job 1161: Subtask save_and_flush_task
[2024-07-14T09:05:35.485+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T07:00:00+00:00 [running]> on host d537c34a4880
[2024-07-14T09:05:35.591+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T07:00:00+00:00'
[2024-07-14T09:05:35.594+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T09:05:35.596+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T09:05:35.604+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T09:05:35.629+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T07:00:00+00:00, execution_date=20240714T070000, start_date=20240714T090535, end_date=20240714T090535
[2024-07-14T09:05:35.667+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T09:05:35.702+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T09:05:35.703+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-14T20:34:56.471+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T20:34:56.517+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T07:00:00+00:00 [queued]>
[2024-07-14T20:34:56.525+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T07:00:00+00:00 [queued]>
[2024-07-14T20:34:56.526+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T20:34:56.560+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 07:00:00+00:00
[2024-07-14T20:34:56.574+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1837) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T20:34:56.580+0000] {standard_task_runner.py:63} INFO - Started process 1852 to run task
[2024-07-14T20:34:56.573+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T07:00:00+00:00', '--job-id', '819', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp00zulczi']
[2024-07-14T20:34:56.593+0000] {standard_task_runner.py:91} INFO - Job 819: Subtask save_and_flush_task
[2024-07-14T20:34:56.670+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T07:00:00+00:00 [running]> on host 77caf7e4b282
[2024-07-14T20:34:56.766+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T07:00:00+00:00'
[2024-07-14T20:34:56.767+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T20:34:56.776+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T20:34:56.777+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T20:34:56.791+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T07:00:00+00:00, execution_date=20240714T070000, start_date=20240714T203456, end_date=20240714T203456
[2024-07-14T20:34:56.816+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T20:34:56.832+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T20:34:56.847+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-15T06:32:30.377+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T06:32:30.404+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T07:00:00+00:00 [queued]>
[2024-07-15T06:32:30.412+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T07:00:00+00:00 [queued]>
[2024-07-15T06:32:30.413+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-15T06:32:30.429+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 07:00:00+00:00
[2024-07-15T06:32:30.439+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T07:00:00+00:00', '--job-id', '232', '--raw', '--subdir', 'DAGS_FOLDER/et_dag.py', '--cfg-path', '/tmp/tmpg5dtvth3']
[2024-07-15T06:32:30.441+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3000) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-15T06:32:30.446+0000] {standard_task_runner.py:91} INFO - Job 232: Subtask save_and_flush_task
[2024-07-15T06:32:30.446+0000] {standard_task_runner.py:63} INFO - Started process 3007 to run task
[2024-07-15T06:32:30.515+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T07:00:00+00:00 [running]> on host 52e7a9c3d832
[2024-07-15T06:32:30.578+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T07:00:00+00:00'
[2024-07-15T06:32:30.581+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T06:32:30.591+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T06:32:30.593+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/et_dag.py", line 38, in trigger_save_and_flush
    logging('Invoking method to save data from records')
TypeError: 'module' object is not callable
[2024-07-15T06:32:30.609+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T07:00:00+00:00, execution_date=20240714T070000, start_date=20240715T063230, end_date=20240715T063230
[2024-07-15T06:32:30.624+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 232 for task save_and_flush_task ('module' object is not callable; 3007)
[2024-07-15T06:32:30.673+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-15T06:32:30.688+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-15T06:32:30.690+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
