[2024-07-14T16:50:56.614+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T16:50:56.704+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T16:30:00+00:00 [queued]>
[2024-07-14T16:50:56.743+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T16:30:00+00:00 [queued]>
[2024-07-14T16:50:56.759+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T16:50:56.821+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 16:30:00+00:00
[2024-07-14T16:50:56.836+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7071) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-14T16:50:56.845+0000] {standard_task_runner.py:63} INFO - Started process 7097 to run task
[2024-07-14T16:50:56.847+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T16:30:00+00:00', '--job-id', '2129', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp8a3slhsl']
[2024-07-14T16:50:56.862+0000] {standard_task_runner.py:91} INFO - Job 2129: Subtask save_and_flush_task
[2024-07-14T16:50:57.088+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T16:30:00+00:00 [running]> on host d537c34a4880
[2024-07-14T16:50:57.339+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T16:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T16:30:00+00:00'
[2024-07-14T16:50:57.345+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T16:50:57.355+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T16:50:57.359+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T16:50:57.387+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T16:30:00+00:00, execution_date=20240714T163000, start_date=20240714T165056, end_date=20240714T165057
[2024-07-14T16:50:57.429+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T16:50:57.533+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T16:50:57.537+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-14T20:35:25.493+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T20:35:25.509+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T16:30:00+00:00 [queued]>
[2024-07-14T20:35:25.514+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T16:30:00+00:00 [queued]>
[2024-07-14T20:35:25.514+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T20:35:25.523+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 16:30:00+00:00
[2024-07-14T20:35:25.527+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2226) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T20:35:25.527+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T16:30:00+00:00', '--job-id', '1008', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp930tlf7x']
[2024-07-14T20:35:25.528+0000] {standard_task_runner.py:63} INFO - Started process 2228 to run task
[2024-07-14T20:35:25.529+0000] {standard_task_runner.py:91} INFO - Job 1008: Subtask save_and_flush_task
[2024-07-14T20:35:25.555+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T16:30:00+00:00 [running]> on host 77caf7e4b282
[2024-07-14T20:35:25.600+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T16:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T16:30:00+00:00'
[2024-07-14T20:35:25.600+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T20:35:25.606+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T20:35:25.606+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T20:35:25.612+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T16:30:00+00:00, execution_date=20240714T163000, start_date=20240714T203525, end_date=20240714T203525
[2024-07-14T20:35:25.627+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T20:35:25.636+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T20:35:25.637+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-15T06:36:49.137+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T06:36:49.169+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T16:30:00+00:00 [queued]>
[2024-07-15T06:36:49.178+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T16:30:00+00:00 [queued]>
[2024-07-15T06:36:49.183+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-15T06:36:49.238+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 16:30:00+00:00
[2024-07-15T06:36:49.245+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T16:30:00+00:00', '--job-id', '599', '--raw', '--subdir', 'DAGS_FOLDER/et_dag.py', '--cfg-path', '/tmp/tmpovtgoj_q']
[2024-07-15T06:36:49.250+0000] {standard_task_runner.py:91} INFO - Job 599: Subtask save_and_flush_task
[2024-07-15T06:36:49.259+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3813) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-15T06:36:49.265+0000] {standard_task_runner.py:63} INFO - Started process 3825 to run task
[2024-07-15T06:36:49.317+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T16:30:00+00:00 [running]> on host 52e7a9c3d832
[2024-07-15T06:36:49.392+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T16:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T16:30:00+00:00'
[2024-07-15T06:36:49.393+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T06:36:49.400+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T06:36:49.405+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/et_dag.py", line 38, in trigger_save_and_flush
    logging('Invoking method to save data from records')
TypeError: 'module' object is not callable
[2024-07-15T06:36:49.428+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T16:30:00+00:00, execution_date=20240714T163000, start_date=20240715T063649, end_date=20240715T063649
[2024-07-15T06:36:49.445+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 599 for task save_and_flush_task ('module' object is not callable; 3825)
[2024-07-15T06:36:49.466+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-15T06:36:49.480+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
