[2024-07-14T13:11:32.019+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T13:11:32.031+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T12:50:00+00:00 [queued]>
[2024-07-14T13:11:32.037+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T12:50:00+00:00 [queued]>
[2024-07-14T13:11:32.038+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T13:11:32.047+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 12:50:00+00:00
[2024-07-14T13:11:32.056+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5520) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-14T13:11:32.057+0000] {standard_task_runner.py:63} INFO - Started process 5525 to run task
[2024-07-14T13:11:32.060+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T12:50:00+00:00', '--job-id', '1655', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpeuh8xli3']
[2024-07-14T13:11:32.062+0000] {standard_task_runner.py:91} INFO - Job 1655: Subtask save_and_flush_task
[2024-07-14T13:11:32.136+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T12:50:00+00:00 [running]> on host d537c34a4880
[2024-07-14T13:11:32.237+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T12:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T12:50:00+00:00'
[2024-07-14T13:11:32.242+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T13:11:32.242+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T13:11:32.243+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T13:11:32.256+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T12:50:00+00:00, execution_date=20240714T125000, start_date=20240714T131132, end_date=20240714T131132
[2024-07-14T13:11:32.285+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T13:11:32.298+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-14T20:35:11.542+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T20:35:11.607+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T12:50:00+00:00 [queued]>
[2024-07-14T20:35:11.621+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T12:50:00+00:00 [queued]>
[2024-07-14T20:35:11.622+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T20:35:11.811+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 12:50:00+00:00
[2024-07-14T20:35:11.827+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2057) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T20:35:11.831+0000] {standard_task_runner.py:63} INFO - Started process 2073 to run task
[2024-07-14T20:35:11.834+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T12:50:00+00:00', '--job-id', '928', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp6jnh0ku4']
[2024-07-14T20:35:11.838+0000] {standard_task_runner.py:91} INFO - Job 928: Subtask save_and_flush_task
[2024-07-14T20:35:12.007+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T12:50:00+00:00 [running]> on host 77caf7e4b282
[2024-07-14T20:35:12.253+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T12:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T12:50:00+00:00'
[2024-07-14T20:35:12.268+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T20:35:12.292+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T20:35:12.294+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T20:35:12.312+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T12:50:00+00:00, execution_date=20240714T125000, start_date=20240714T203511, end_date=20240714T203512
[2024-07-14T20:35:12.382+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T20:35:12.406+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T20:35:12.412+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-15T06:34:40.205+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T06:34:40.225+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T12:50:00+00:00 [queued]>
[2024-07-15T06:34:40.231+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T12:50:00+00:00 [queued]>
[2024-07-15T06:34:40.234+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-15T06:34:40.245+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 12:50:00+00:00
[2024-07-15T06:34:40.253+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3443) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-15T06:34:40.253+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T12:50:00+00:00', '--job-id', '433', '--raw', '--subdir', 'DAGS_FOLDER/et_dag.py', '--cfg-path', '/tmp/tmp9x5fe_t8']
[2024-07-15T06:34:40.258+0000] {standard_task_runner.py:63} INFO - Started process 3453 to run task
[2024-07-15T06:34:40.258+0000] {standard_task_runner.py:91} INFO - Job 433: Subtask save_and_flush_task
[2024-07-15T06:34:40.310+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T12:50:00+00:00 [running]> on host 52e7a9c3d832
[2024-07-15T06:34:40.364+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T12:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T12:50:00+00:00'
[2024-07-15T06:34:40.364+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T06:34:40.373+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T06:34:40.377+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/et_dag.py", line 38, in trigger_save_and_flush
    logging('Invoking method to save data from records')
TypeError: 'module' object is not callable
[2024-07-15T06:34:40.392+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T12:50:00+00:00, execution_date=20240714T125000, start_date=20240715T063440, end_date=20240715T063440
[2024-07-15T06:34:40.467+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 433 for task save_and_flush_task ('module' object is not callable; 3453)
[2024-07-15T06:34:40.480+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-15T06:34:40.499+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-15T06:34:40.502+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
