[2024-07-14T09:05:34.269+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T09:05:34.337+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T06:10:00+00:00 [queued]>
[2024-07-14T09:05:34.383+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T06:10:00+00:00 [queued]>
[2024-07-14T09:05:34.390+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T09:05:34.507+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 06:10:00+00:00
[2024-07-14T09:05:34.525+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3603) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-14T09:05:34.530+0000] {standard_task_runner.py:63} INFO - Started process 3627 to run task
[2024-07-14T09:05:34.528+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T06:10:00+00:00', '--job-id', '1157', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpntulf5b2']
[2024-07-14T09:05:34.532+0000] {standard_task_runner.py:91} INFO - Job 1157: Subtask save_and_flush_task
[2024-07-14T09:05:34.748+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T06:10:00+00:00 [running]> on host d537c34a4880
[2024-07-14T09:05:34.875+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T06:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T06:10:00+00:00'
[2024-07-14T09:05:34.878+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T09:05:34.879+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T09:05:34.880+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T09:05:34.895+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T06:10:00+00:00, execution_date=20240714T061000, start_date=20240714T090534, end_date=20240714T090534
[2024-07-14T09:05:34.959+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T09:05:35.001+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T09:05:35.007+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-14T20:34:52.662+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T20:34:52.679+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T06:10:00+00:00 [queued]>
[2024-07-14T20:34:52.682+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T06:10:00+00:00 [queued]>
[2024-07-14T20:34:52.683+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T20:34:52.689+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 06:10:00+00:00
[2024-07-14T20:34:52.693+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1807) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T20:34:52.694+0000] {standard_task_runner.py:63} INFO - Started process 1811 to run task
[2024-07-14T20:34:52.693+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T06:10:00+00:00', '--job-id', '801', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpjp0h25nh']
[2024-07-14T20:34:52.694+0000] {standard_task_runner.py:91} INFO - Job 801: Subtask save_and_flush_task
[2024-07-14T20:34:52.721+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T06:10:00+00:00 [running]> on host 77caf7e4b282
[2024-07-14T20:34:52.767+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T06:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T06:10:00+00:00'
[2024-07-14T20:34:52.767+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T20:34:52.773+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T20:34:52.774+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T20:34:52.780+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T06:10:00+00:00, execution_date=20240714T061000, start_date=20240714T203452, end_date=20240714T203452
[2024-07-14T20:34:52.792+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T20:34:52.804+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T20:34:52.804+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-15T06:32:29.404+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T06:32:29.438+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T06:10:00+00:00 [queued]>
[2024-07-15T06:32:29.444+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T06:10:00+00:00 [queued]>
[2024-07-15T06:32:29.445+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-15T06:32:29.470+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 06:10:00+00:00
[2024-07-15T06:32:29.477+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2969) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-15T06:32:29.483+0000] {standard_task_runner.py:63} INFO - Started process 2980 to run task
[2024-07-15T06:32:29.481+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T06:10:00+00:00', '--job-id', '219', '--raw', '--subdir', 'DAGS_FOLDER/et_dag.py', '--cfg-path', '/tmp/tmp7en1wxa0']
[2024-07-15T06:32:29.488+0000] {standard_task_runner.py:91} INFO - Job 219: Subtask save_and_flush_task
[2024-07-15T06:32:29.562+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T06:10:00+00:00 [running]> on host 52e7a9c3d832
[2024-07-15T06:32:29.686+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T06:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T06:10:00+00:00'
[2024-07-15T06:32:29.692+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T06:32:29.702+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T06:32:29.704+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/et_dag.py", line 38, in trigger_save_and_flush
    logging('Invoking method to save data from records')
TypeError: 'module' object is not callable
[2024-07-15T06:32:29.744+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T06:10:00+00:00, execution_date=20240714T061000, start_date=20240715T063229, end_date=20240715T063229
[2024-07-15T06:32:29.804+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 219 for task save_and_flush_task ('module' object is not callable; 2980)
[2024-07-15T06:32:29.834+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-15T06:32:29.852+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-15T06:32:29.855+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
