[2024-07-14T09:05:26.250+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T09:05:26.312+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T03:30:00+00:00 [queued]>
[2024-07-14T09:05:26.328+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T03:30:00+00:00 [queued]>
[2024-07-14T09:05:26.329+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T09:05:26.408+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 03:30:00+00:00
[2024-07-14T09:05:26.418+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3554) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-14T09:05:26.428+0000] {standard_task_runner.py:63} INFO - Started process 3580 to run task
[2024-07-14T09:05:26.480+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T03:30:00+00:00', '--job-id', '1140', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpwkc31ycz']
[2024-07-14T09:05:26.509+0000] {standard_task_runner.py:91} INFO - Job 1140: Subtask save_and_flush_task
[2024-07-14T09:05:26.957+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T03:30:00+00:00 [running]> on host d537c34a4880
[2024-07-14T09:05:27.276+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T03:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T03:30:00+00:00'
[2024-07-14T09:05:27.280+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T09:05:27.284+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T09:05:27.285+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T09:05:27.293+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T03:30:00+00:00, execution_date=20240714T033000, start_date=20240714T090526, end_date=20240714T090527
[2024-07-14T09:05:27.359+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T09:05:27.384+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T09:05:27.402+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-14T20:34:44.760+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T20:34:44.779+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T03:30:00+00:00 [queued]>
[2024-07-14T20:34:44.784+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T03:30:00+00:00 [queued]>
[2024-07-14T20:34:44.784+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T20:34:44.795+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 03:30:00+00:00
[2024-07-14T20:34:44.798+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1717) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T20:34:44.799+0000] {standard_task_runner.py:63} INFO - Started process 1721 to run task
[2024-07-14T20:34:44.799+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T03:30:00+00:00', '--job-id', '758', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpcuvfzll8']
[2024-07-14T20:34:44.802+0000] {standard_task_runner.py:91} INFO - Job 758: Subtask save_and_flush_task
[2024-07-14T20:34:44.832+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T03:30:00+00:00 [running]> on host 77caf7e4b282
[2024-07-14T20:34:44.890+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T03:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T03:30:00+00:00'
[2024-07-14T20:34:44.894+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T20:34:44.902+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T20:34:44.904+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T20:34:44.917+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T03:30:00+00:00, execution_date=20240714T033000, start_date=20240714T203444, end_date=20240714T203444
[2024-07-14T20:34:44.940+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T20:34:44.955+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T20:34:44.959+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-15T06:31:25.468+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T06:31:25.531+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T03:30:00+00:00 [queued]>
[2024-07-15T06:31:25.541+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T03:30:00+00:00 [queued]>
[2024-07-15T06:31:25.548+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-15T06:31:25.571+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 03:30:00+00:00
[2024-07-15T06:31:25.581+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2762) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-15T06:31:25.585+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T03:30:00+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/et_dag.py', '--cfg-path', '/tmp/tmpkn3fyd46']
[2024-07-15T06:31:25.586+0000] {standard_task_runner.py:63} INFO - Started process 2771 to run task
[2024-07-15T06:31:25.594+0000] {standard_task_runner.py:91} INFO - Job 123: Subtask save_and_flush_task
[2024-07-15T06:31:25.685+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T03:30:00+00:00 [running]> on host 52e7a9c3d832
[2024-07-15T06:31:25.807+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T03:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T03:30:00+00:00'
[2024-07-15T06:31:25.808+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T06:31:25.821+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T06:31:25.822+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/et_dag.py", line 38, in trigger_save_and_flush
    logging('Invoking method to save data from records')
TypeError: 'module' object is not callable
[2024-07-15T06:31:25.835+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T03:30:00+00:00, execution_date=20240714T033000, start_date=20240715T063125, end_date=20240715T063125
[2024-07-15T06:31:25.847+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 123 for task save_and_flush_task ('module' object is not callable; 2771)
[2024-07-15T06:31:25.867+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-15T06:31:25.882+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-15T06:31:25.885+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
