[2024-07-14T09:05:11.899+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T09:05:11.951+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T01:40:00+00:00 [queued]>
[2024-07-14T09:05:11.964+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T01:40:00+00:00 [queued]>
[2024-07-14T09:05:11.966+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T09:05:11.994+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 01:40:00+00:00
[2024-07-14T09:05:12.025+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3497) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-14T09:05:12.027+0000] {standard_task_runner.py:63} INFO - Started process 3518 to run task
[2024-07-14T09:05:12.029+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T01:40:00+00:00', '--job-id', '1121', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpkfijdtna']
[2024-07-14T09:05:12.037+0000] {standard_task_runner.py:91} INFO - Job 1121: Subtask save_and_flush_task
[2024-07-14T09:05:12.161+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T01:40:00+00:00 [running]> on host d537c34a4880
[2024-07-14T09:05:12.497+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T01:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T01:40:00+00:00'
[2024-07-14T09:05:12.523+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T09:05:12.526+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T09:05:12.531+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T09:05:12.572+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T01:40:00+00:00, execution_date=20240714T014000, start_date=20240714T090511, end_date=20240714T090512
[2024-07-14T09:05:12.638+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T09:05:12.839+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-14T20:34:40.018+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T20:34:40.061+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T01:40:00+00:00 [queued]>
[2024-07-14T20:34:40.076+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T01:40:00+00:00 [queued]>
[2024-07-14T20:34:40.077+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T20:34:40.200+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 01:40:00+00:00
[2024-07-14T20:34:40.209+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1640) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T20:34:40.211+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T01:40:00+00:00', '--job-id', '724', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmppkbfw98i']
[2024-07-14T20:34:40.226+0000] {standard_task_runner.py:91} INFO - Job 724: Subtask save_and_flush_task
[2024-07-14T20:34:40.216+0000] {standard_task_runner.py:63} INFO - Started process 1656 to run task
[2024-07-14T20:34:40.350+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T01:40:00+00:00 [running]> on host 77caf7e4b282
[2024-07-14T20:34:40.432+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T01:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T01:40:00+00:00'
[2024-07-14T20:34:40.435+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T20:34:40.452+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T20:34:40.457+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T20:34:40.466+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T01:40:00+00:00, execution_date=20240714T014000, start_date=20240714T203440, end_date=20240714T203440
[2024-07-14T20:34:40.497+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T20:34:40.532+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-15T06:30:20.956+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T06:30:20.975+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T01:40:00+00:00 [queued]>
[2024-07-15T06:30:20.980+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T01:40:00+00:00 [queued]>
[2024-07-15T06:30:20.982+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-15T06:30:20.990+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 01:40:00+00:00
[2024-07-15T06:30:20.994+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2601) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-15T06:30:20.995+0000] {standard_task_runner.py:63} INFO - Started process 2604 to run task
[2024-07-15T06:30:20.995+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T01:40:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/et_dag.py', '--cfg-path', '/tmp/tmp6rxbcdyc']
[2024-07-15T06:30:20.996+0000] {standard_task_runner.py:91} INFO - Job 52: Subtask save_and_flush_task
[2024-07-15T06:30:21.023+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T01:40:00+00:00 [running]> on host 52e7a9c3d832
[2024-07-15T06:30:21.063+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T01:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T01:40:00+00:00'
[2024-07-15T06:30:21.064+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T06:30:21.070+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T06:30:21.071+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/et_dag.py", line 38, in trigger_save_and_flush
    logging('Invoking method to save data from records')
TypeError: 'module' object is not callable
[2024-07-15T06:30:21.077+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T01:40:00+00:00, execution_date=20240714T014000, start_date=20240715T063020, end_date=20240715T063021
[2024-07-15T06:30:21.083+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 52 for task save_and_flush_task ('module' object is not callable; 2604)
[2024-07-15T06:30:21.093+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-15T06:30:21.099+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
