[2024-07-14T13:31:17.487+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T13:31:17.684+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T13:20:00+00:00 [queued]>
[2024-07-14T13:31:17.731+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T13:20:00+00:00 [queued]>
[2024-07-14T13:31:17.737+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T13:31:17.794+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 13:20:00+00:00
[2024-07-14T13:31:17.830+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5676) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-14T13:31:17.840+0000] {standard_task_runner.py:63} INFO - Started process 5698 to run task
[2024-07-14T13:31:17.839+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T13:20:00+00:00', '--job-id', '1702', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp8x6hc4wo']
[2024-07-14T13:31:17.879+0000] {standard_task_runner.py:91} INFO - Job 1702: Subtask save_and_flush_task
[2024-07-14T13:31:17.992+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T13:20:00+00:00 [running]> on host d537c34a4880
[2024-07-14T13:31:18.304+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T13:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T13:20:00+00:00'
[2024-07-14T13:31:18.310+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T13:31:18.312+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T13:31:18.312+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T13:31:18.351+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T13:20:00+00:00, execution_date=20240714T132000, start_date=20240714T133117, end_date=20240714T133118
[2024-07-14T13:31:18.458+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T13:31:18.536+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T13:31:18.545+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-14T20:35:12.251+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T20:35:12.295+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T13:20:00+00:00 [queued]>
[2024-07-14T20:35:12.315+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T13:20:00+00:00 [queued]>
[2024-07-14T20:35:12.317+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T20:35:12.368+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 13:20:00+00:00
[2024-07-14T20:35:12.379+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2076) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T20:35:12.384+0000] {standard_task_runner.py:63} INFO - Started process 2086 to run task
[2024-07-14T20:35:12.385+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T13:20:00+00:00', '--job-id', '938', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpryofg31k']
[2024-07-14T20:35:12.395+0000] {standard_task_runner.py:91} INFO - Job 938: Subtask save_and_flush_task
[2024-07-14T20:35:12.445+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T13:20:00+00:00 [running]> on host 77caf7e4b282
[2024-07-14T20:35:12.670+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T13:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T13:20:00+00:00'
[2024-07-14T20:35:12.677+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T20:35:12.694+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T20:35:12.695+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T20:35:12.702+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T13:20:00+00:00, execution_date=20240714T132000, start_date=20240714T203512, end_date=20240714T203512
[2024-07-14T20:35:12.747+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T20:35:12.817+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T20:35:12.818+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-15T06:35:43.589+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T06:35:43.610+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T13:20:00+00:00 [queued]>
[2024-07-15T06:35:43.616+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T13:20:00+00:00 [queued]>
[2024-07-15T06:35:43.617+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-15T06:35:43.632+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 13:20:00+00:00
[2024-07-15T06:35:43.636+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3585) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-15T06:35:43.638+0000] {standard_task_runner.py:63} INFO - Started process 3594 to run task
[2024-07-15T06:35:43.637+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T13:20:00+00:00', '--job-id', '492', '--raw', '--subdir', 'DAGS_FOLDER/et_dag.py', '--cfg-path', '/tmp/tmpkvsvgu__']
[2024-07-15T06:35:43.640+0000] {standard_task_runner.py:91} INFO - Job 492: Subtask save_and_flush_task
[2024-07-15T06:35:43.690+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T13:20:00+00:00 [running]> on host 52e7a9c3d832
[2024-07-15T06:35:43.778+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T13:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T13:20:00+00:00'
[2024-07-15T06:35:43.780+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T06:35:43.792+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T06:35:43.798+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/et_dag.py", line 38, in trigger_save_and_flush
    logging('Invoking method to save data from records')
TypeError: 'module' object is not callable
[2024-07-15T06:35:43.814+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T13:20:00+00:00, execution_date=20240714T132000, start_date=20240715T063543, end_date=20240715T063543
[2024-07-15T06:35:43.831+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 492 for task save_and_flush_task ('module' object is not callable; 3594)
[2024-07-15T06:35:43.865+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-15T06:35:43.882+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-15T06:35:43.884+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
