[2024-07-14T17:07:41.545+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T17:07:41.597+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T16:50:00+00:00 [queued]>
[2024-07-14T17:07:41.611+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T16:50:00+00:00 [queued]>
[2024-07-14T17:07:41.613+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T17:07:41.670+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 16:50:00+00:00
[2024-07-14T17:07:41.755+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7244) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-14T17:07:41.762+0000] {standard_task_runner.py:63} INFO - Started process 7268 to run task
[2024-07-14T17:07:41.769+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T16:50:00+00:00', '--job-id', '2180', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmptemvyg65']
[2024-07-14T17:07:41.802+0000] {standard_task_runner.py:91} INFO - Job 2180: Subtask save_and_flush_task
[2024-07-14T17:07:41.944+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T16:50:00+00:00 [running]> on host d537c34a4880
[2024-07-14T17:07:42.264+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T16:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T16:50:00+00:00'
[2024-07-14T17:07:42.267+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T17:07:42.270+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T17:07:42.274+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T17:07:42.289+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T16:50:00+00:00, execution_date=20240714T165000, start_date=20240714T170741, end_date=20240714T170742
[2024-07-14T17:07:42.337+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T17:07:42.384+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T17:07:42.393+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-14T20:35:27.586+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T20:35:27.601+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T16:50:00+00:00 [queued]>
[2024-07-14T20:35:27.605+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T16:50:00+00:00 [queued]>
[2024-07-14T20:35:27.605+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T20:35:27.611+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 16:50:00+00:00
[2024-07-14T20:35:27.615+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2237) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T20:35:27.615+0000] {standard_task_runner.py:63} INFO - Started process 2241 to run task
[2024-07-14T20:35:27.615+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T16:50:00+00:00', '--job-id', '1012', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp1_40qmj9']
[2024-07-14T20:35:27.616+0000] {standard_task_runner.py:91} INFO - Job 1012: Subtask save_and_flush_task
[2024-07-14T20:35:27.642+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T16:50:00+00:00 [running]> on host 77caf7e4b282
[2024-07-14T20:35:27.685+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T16:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T16:50:00+00:00'
[2024-07-14T20:35:27.687+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T20:35:27.693+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T20:35:27.694+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T20:35:27.701+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T16:50:00+00:00, execution_date=20240714T165000, start_date=20240714T203527, end_date=20240714T203527
[2024-07-14T20:35:27.714+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T20:35:27.723+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T20:35:27.724+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-15T06:36:49.403+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T06:36:49.436+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T16:50:00+00:00 [queued]>
[2024-07-15T06:36:49.444+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T16:50:00+00:00 [queued]>
[2024-07-15T06:36:49.446+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-15T06:36:49.461+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 16:50:00+00:00
[2024-07-15T06:36:49.474+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3828) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-15T06:36:49.473+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T16:50:00+00:00', '--job-id', '603', '--raw', '--subdir', 'DAGS_FOLDER/et_dag.py', '--cfg-path', '/tmp/tmpqn1871k3']
[2024-07-15T06:36:49.481+0000] {standard_task_runner.py:63} INFO - Started process 3835 to run task
[2024-07-15T06:36:49.485+0000] {standard_task_runner.py:91} INFO - Job 603: Subtask save_and_flush_task
[2024-07-15T06:36:49.553+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T16:50:00+00:00 [running]> on host 52e7a9c3d832
[2024-07-15T06:36:49.631+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T16:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T16:50:00+00:00'
[2024-07-15T06:36:49.633+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T06:36:49.646+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T06:36:49.647+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/et_dag.py", line 38, in trigger_save_and_flush
    logging('Invoking method to save data from records')
TypeError: 'module' object is not callable
[2024-07-15T06:36:49.662+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T16:50:00+00:00, execution_date=20240714T165000, start_date=20240715T063649, end_date=20240715T063649
[2024-07-15T06:36:49.683+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 603 for task save_and_flush_task ('module' object is not callable; 3835)
[2024-07-15T06:36:49.712+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-15T06:36:49.720+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
