[2024-07-14T10:11:56.244+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T10:11:56.396+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T09:50:00+00:00 [queued]>
[2024-07-14T10:11:56.444+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T09:50:00+00:00 [queued]>
[2024-07-14T10:11:56.454+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T10:11:56.676+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 09:50:00+00:00
[2024-07-14T10:11:56.707+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4302) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-14T10:11:56.723+0000] {standard_task_runner.py:63} INFO - Started process 4326 to run task
[2024-07-14T10:11:56.712+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T09:50:00+00:00', '--job-id', '1276', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpk1hgz8vm']
[2024-07-14T10:11:56.738+0000] {standard_task_runner.py:91} INFO - Job 1276: Subtask save_and_flush_task
[2024-07-14T10:11:56.951+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T09:50:00+00:00 [running]> on host d537c34a4880
[2024-07-14T10:11:57.268+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T09:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T09:50:00+00:00'
[2024-07-14T10:11:57.300+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T10:11:57.465+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T10:11:57.474+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T10:11:57.497+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T09:50:00+00:00, execution_date=20240714T095000, start_date=20240714T101156, end_date=20240714T101157
[2024-07-14T10:11:57.589+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T10:11:57.631+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T10:11:57.698+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-14T20:35:03.155+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T20:35:03.253+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T09:50:00+00:00 [queued]>
[2024-07-14T20:35:03.265+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T09:50:00+00:00 [queued]>
[2024-07-14T20:35:03.267+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T20:35:03.351+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 09:50:00+00:00
[2024-07-14T20:35:03.368+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1940) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T20:35:03.371+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T09:50:00+00:00', '--job-id', '870', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp08p72tvk']
[2024-07-14T20:35:03.379+0000] {standard_task_runner.py:91} INFO - Job 870: Subtask save_and_flush_task
[2024-07-14T20:35:03.374+0000] {standard_task_runner.py:63} INFO - Started process 1951 to run task
[2024-07-14T20:35:03.483+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T09:50:00+00:00 [running]> on host 77caf7e4b282
[2024-07-14T20:35:03.558+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T09:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T09:50:00+00:00'
[2024-07-14T20:35:03.559+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T20:35:03.565+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T20:35:03.566+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T20:35:03.571+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T09:50:00+00:00, execution_date=20240714T095000, start_date=20240714T203503, end_date=20240714T203503
[2024-07-14T20:35:03.582+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T20:35:03.595+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T20:35:03.596+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-15T06:33:35.779+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T06:33:35.817+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T09:50:00+00:00 [queued]>
[2024-07-15T06:33:35.825+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T09:50:00+00:00 [queued]>
[2024-07-15T06:33:35.825+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-15T06:33:35.845+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 09:50:00+00:00
[2024-07-15T06:33:35.855+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T09:50:00+00:00', '--job-id', '332', '--raw', '--subdir', 'DAGS_FOLDER/et_dag.py', '--cfg-path', '/tmp/tmppxhrhstz']
[2024-07-15T06:33:35.858+0000] {standard_task_runner.py:91} INFO - Job 332: Subtask save_and_flush_task
[2024-07-15T06:33:35.859+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3224) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-15T06:33:35.860+0000] {standard_task_runner.py:63} INFO - Started process 3233 to run task
[2024-07-15T06:33:35.896+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T09:50:00+00:00 [running]> on host 52e7a9c3d832
[2024-07-15T06:33:35.978+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T09:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T09:50:00+00:00'
[2024-07-15T06:33:35.980+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T06:33:35.996+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T06:33:35.998+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/et_dag.py", line 38, in trigger_save_and_flush
    logging('Invoking method to save data from records')
TypeError: 'module' object is not callable
[2024-07-15T06:33:36.010+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T09:50:00+00:00, execution_date=20240714T095000, start_date=20240715T063335, end_date=20240715T063336
[2024-07-15T06:33:36.022+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 332 for task save_and_flush_task ('module' object is not callable; 3233)
[2024-07-15T06:33:36.042+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-15T06:33:36.051+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
