[2024-07-14T09:05:43.634+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T09:05:43.652+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T08:40:00+00:00 [queued]>
[2024-07-14T09:05:43.656+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T08:40:00+00:00 [queued]>
[2024-07-14T09:05:43.657+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T09:05:43.669+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 08:40:00+00:00
[2024-07-14T09:05:43.675+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3646) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-14T09:05:43.677+0000] {standard_task_runner.py:63} INFO - Started process 3658 to run task
[2024-07-14T09:05:43.676+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T08:40:00+00:00', '--job-id', '1171', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpzv4y67kf']
[2024-07-14T09:05:43.680+0000] {standard_task_runner.py:91} INFO - Job 1171: Subtask save_and_flush_task
[2024-07-14T09:05:43.718+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T08:40:00+00:00 [running]> on host d537c34a4880
[2024-07-14T09:05:43.824+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T08:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T08:40:00+00:00'
[2024-07-14T09:05:43.826+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T09:05:43.826+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T09:05:43.827+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T09:05:43.831+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T08:40:00+00:00, execution_date=20240714T084000, start_date=20240714T090543, end_date=20240714T090543
[2024-07-14T09:05:43.881+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T09:05:43.891+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T09:05:43.893+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-14T20:34:59.573+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T20:34:59.642+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T08:40:00+00:00 [queued]>
[2024-07-14T20:34:59.650+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T08:40:00+00:00 [queued]>
[2024-07-14T20:34:59.652+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T20:34:59.754+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 08:40:00+00:00
[2024-07-14T20:34:59.765+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T08:40:00+00:00', '--job-id', '843', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmps1tvybfc']
[2024-07-14T20:34:59.774+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1888) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T20:34:59.776+0000] {standard_task_runner.py:91} INFO - Job 843: Subtask save_and_flush_task
[2024-07-14T20:34:59.776+0000] {standard_task_runner.py:63} INFO - Started process 1900 to run task
[2024-07-14T20:34:59.827+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T08:40:00+00:00 [running]> on host 77caf7e4b282
[2024-07-14T20:34:59.941+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T08:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T08:40:00+00:00'
[2024-07-14T20:34:59.944+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T20:34:59.954+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-14T20:34:59.954+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T20:34:59.967+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T08:40:00+00:00, execution_date=20240714T084000, start_date=20240714T203459, end_date=20240714T203459
[2024-07-14T20:35:00.009+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T20:35:00.026+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T20:35:00.029+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-15T06:33:34.626+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T06:33:34.663+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T08:40:00+00:00 [queued]>
[2024-07-15T06:33:34.673+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T08:40:00+00:00 [queued]>
[2024-07-15T06:33:34.673+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-15T06:33:34.693+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_and_flush_task> on 2024-07-14 08:40:00+00:00
[2024-07-15T06:33:34.706+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3180) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-15T06:33:34.709+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'save_spread_values', 'save_and_flush_task', 'scheduled__2024-07-14T08:40:00+00:00', '--job-id', '311', '--raw', '--subdir', 'DAGS_FOLDER/et_dag.py', '--cfg-path', '/tmp/tmp1cfufot4']
[2024-07-15T06:33:34.712+0000] {standard_task_runner.py:63} INFO - Started process 3193 to run task
[2024-07-15T06:33:34.714+0000] {standard_task_runner.py:91} INFO - Job 311: Subtask save_and_flush_task
[2024-07-15T06:33:34.775+0000] {task_command.py:426} INFO - Running <TaskInstance: save_spread_values.save_and_flush_task scheduled__2024-07-14T08:40:00+00:00 [running]> on host 52e7a9c3d832
[2024-07-15T06:33:34.865+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='save_spread_values' AIRFLOW_CTX_TASK_ID='save_and_flush_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T08:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T08:40:00+00:00'
[2024-07-15T06:33:34.868+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T06:33:34.876+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T06:33:34.877+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/et_dag.py", line 38, in trigger_save_and_flush
    logging('Invoking method to save data from records')
TypeError: 'module' object is not callable
[2024-07-15T06:33:34.894+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=save_spread_values, task_id=save_and_flush_task, run_id=scheduled__2024-07-14T08:40:00+00:00, execution_date=20240714T084000, start_date=20240715T063334, end_date=20240715T063334
[2024-07-15T06:33:34.913+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 311 for task save_and_flush_task ('module' object is not callable; 3193)
[2024-07-15T06:33:34.941+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-15T06:33:34.967+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-15T06:33:34.976+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
